version: '3.3'
services:
  db:
    image: m.daocloud.io/docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local